<!DOCTYPE html>
<html lang="en"><head>
<script src="cgots2026_files/libs/clipboard/clipboard.min.js"></script>
<script src="cgots2026_files/libs/quarto-html/tabby.min.js"></script>
<script src="cgots2026_files/libs/quarto-html/popper.min.js"></script>
<script src="cgots2026_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="cgots2026_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="cgots2026_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="cgots2026_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="cgots2026_files/libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="cgots2026_files/libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="cgots2026_files/libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Karl Ho">
  <meta name="author" content="John Marion Glendenning">
  <title>cgots2026</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="cgots2026_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="cgots2026_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="cgots2026_files/libs/revealjs/dist/theme/quarto-99eeafcedac04850354b682963cedae3.css">
  <link rel="stylesheet" href="qslides_1.css">
  <link href="cgots2026_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="cgots2026_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="cgots2026_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="cgots2026_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section>
<section id="section" class="title-slide slide level1 center">
<h1></h1>
<div id="title-slide" class="center">
<h3>
Generational Cleavages in Media Effects: Evidence from Taiwan’s Presidential Elections
</h3>
<br>
<br>

<h4>
Karl Ho
</h4>
<h6>
University of Texas at Dallas
</h6>
<br>

<h4>
John Marion Glendenning
</h4>
<h6>
University of Texas at Dallas
</h6>
</div>
<div class="footer">
<h4>
Prepared for presentation at the Conference Group on Taiwan Studies, 2026.
</h4>
</div>
</section>
<section id="two-headlines-one-month-apart" class="slide level2">
<h2>Two Headlines, One Month Apart</h2>
<blockquote>
<p><strong>用「AI虛擬市民」做民調準嗎？「矽基民調」模擬民意</strong> <em>Are AI virtual citizens accurate for polling?</em> 風傳媒 Storm Media · 7 August 2026</p>
</blockquote>
<blockquote>
<p><strong>15分鐘訪完十萬人 … 市調巨頭為何仍要找真人？</strong> <em>100,000 interviews in 15 minutes — so why do market research giants still want real people?</em> 未來城市＠天下 CommonWealth · 4 September 2026</p>
</blockquote>
<div class="fragment">
<p>Taiwanese phone polls face <strong>90% refusal rates</strong>. TPOC now sells silicon-sample polling at NT$100 per question — benchmarked at <strong>4.56 pp</strong> average error against real phone surveys.</p>
</div>
<div class="fragment">
<p>The alternative to survey research is no longer hypothetical.</p>
</div>
</section>
<section id="the-warning-that-decides-this-paper" class="slide level2">
<h2>The Warning That Decides This Paper</h2>
<p>TPOC’s own research director reports the models <strong>stereotype by age</strong>:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th>Model’s preset</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>35–54</td>
<td>most steadfast, calm, responsible</td>
</tr>
<tr class="even">
<td>Highly educated</td>
<td>rational verifiers</td>
</tr>
<tr class="odd">
<td>Elderly</td>
<td>conservative, hesitant</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><strong>A study of generational cleavage cannot use a method that already holds beliefs about generations.</strong></p>
</div>
<div class="fragment">
<p>A Bayesian network holds none. Cohort probabilities are estimated; where thin, the smoothing is a stated prior with a known weight.</p>
</div>
</section>
<section id="a-cleavage-that-is-closing" class="slide level2">
<h2>A Cleavage That Is Closing</h2>
<p>Taiwanese identity has moved one direction for three decades.</p>
<div class="fragment">
<p><strong>Over 60 in 2024:</strong> roughly split between exclusively Taiwanese and dual identity</p>
<p><strong>Under 30:</strong> overwhelmingly Taiwanese</p>
</div>
<div class="fragment">
<p>Usually read as a story about <strong>where Taiwan is heading</strong>.</p>
<p>We ask a different question — about <strong>how political influence works</strong> once a cleavage closes.</p>
</div>
</section>
<section id="the-argument" class="slide level2">
<h2>The Argument</h2>
<p>Achen and Wang (2017): Taiwanese voting is organized by national identity.</p>
<p>That is a claim about the electorate <strong>in aggregate</strong>.</p>
<div class="fragment">
<p>But a variable can organize an electorate while losing its power to <strong>discriminate within a subgroup</strong>.</p>
</div>
<div class="fragment">
<p>If nearly all young voters identify as Taiwanese, identity tells you little about how one young voter differs from another.</p>
</div>
<div class="fragment">
<p><strong>Hypothesis:</strong> media fills that space — mattering <em>more</em>, not less, for the cohort whose identity is most settled.</p>
<p>Reach and effect are different quantities.</p>
</div>
</section>
<section id="three-elections" class="slide level2">
<h2>Three Elections</h2>
<table class="caption-top">
<colgroup>
<col style="width: 18%">
<col style="width: 24%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>Result</th>
<th>Generational note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2016</td>
<td>Tsai 56.1 / Chu 31.0 / Soong 12.8</td>
<td>Post-Sunflower</td>
</tr>
<tr class="even">
<td>2020</td>
<td>Tsai 57.1 / Han 38.6 / Soong 4.3</td>
<td>Hong Kong shock</td>
</tr>
<tr class="odd">
<td>2024</td>
<td>Lai 40.1 / Hou 33.5 / <strong>Ko 26.5</strong></td>
<td>Third force concentrated <strong>under 40</strong></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>2024 is the puzzle: the cohort with the <strong>most</strong> Taiwan-centric identity declined to vote for the party that owns that position.</p>
</div>
</section>
<section id="design" class="slide level2">
<h2>Design</h2>
<p><span class="math display">\[\Delta_a(m) = P\!\left(Y \mid do(M = m),\, A = a\right) - P\!\left(Y \mid A = a\right)\]</span></p>
<p>Change in outcome within age band <span class="math inline">\(a\)</span>, measured against <strong>that band’s own baseline</strong>.</p>
<div class="fragment">
<ul>
<li class="fragment">Latent class segmentation, then a year-specific <strong>Bayesian network</strong></li>
<li class="fragment">Identity → cross-Strait position on the causal spine</li>
<li class="fragment">Synthetic microdata at 5× observed size</li>
<li class="fragment">Interventions by <strong>graph mutilation</strong> — delete edges into the node, then sample</li>
</ul>
</div>
<div class="fragment">
<p>That last step separates <span class="math inline">\(do(M=m)\)</span> from conditioning — necessary, because Taiwanese voters select media consistent with identity.</p>
</div>
</section></section>
<section>
<section id="findings" class="title-slide slide level1 center">
<h1>Findings</h1>

</section>
<section id="media-effects-by-cohort" class="slide level2">
<h2>Media Effects by Cohort</h2>
<div class="columns">
<div class="column" style="width:62%;">
<p><a href="output/figures/figG1_media_by_cohort.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img data-src="output/figures/figG1_media_by_cohort.png"></a></p>
</div><div class="column" style="width:38%;">
<p><strong>Monotonic in every wave.</strong> Rank correlation with age: −0.9, −0.8, −0.9.</p>
<p>. . .</p>
<p>Ages 20–29: <strong>10.2 → 15.4 → 22.6</strong></p>
<p>Ages 60+: 3.0 → 6.4 → 6.8</p>
<p>. . .</p>
<p>The gap is <strong>widening</strong>.</p>
</div></div>
</section>
<section id="what-media-competes-against" class="slide level2">
<h2>What Media Competes Against</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><a href="output/figures/figG2_competition_by_cohort.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img data-src="output/figures/figG2_competition_by_cohort.png"></a></p>
</div><div class="column" style="width:40%;">
<p>Identity-to-media ratio, ages 60+:</p>
<p><strong>22.9 → 10.6 → 10.8</strong></p>
<p>. . .</p>
<p>Ages 20–29:</p>
<p><strong>4.8 → 3.1 → 0.99</strong></p>
<p>. . .</p>
<p>In 2024 the two interventions move the youngest cohort by the <strong>same amount</strong>.</p>
</div></div>
</section>
<section id="the-number-that-matters" class="slide level2">
<h2>The Number That Matters</h2>
<p><strong>2024, voters aged 20–29:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Intervention</th>
<th style="text-align: right;">Effect on DPP share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>National identity</td>
<td style="text-align: right;">22.3 pp</td>
</tr>
<tr class="even">
<td><strong>Media exposure</strong></td>
<td style="text-align: right;"><strong>22.6 pp</strong></td>
</tr>
<tr class="odd">
<td>Cross-Strait position</td>
<td style="text-align: right;">16.0 pp</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Television news moves these voters <strong>as much as national identity does</strong>.</p>
</div>
<div class="fragment">
<p>Eight years earlier the ratio was 4.8 to 1.</p>
</div>
</section>
<section id="is-it-really-homogeneity" class="slide level2">
<h2>Is It Really Homogeneity?</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p><a href="output/figures/figG3_mechanism.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img data-src="output/figures/figG3_mechanism.png"></a></p>
</div><div class="column" style="width:42%;">
<p>Identity entropy rises with age: <strong>0.51 → 0.82</strong></p>
<p>Correlates at <strong>0.78</strong> with the identity/media ratio.</p>
<p>. . .</p>
<p><strong>Media entropy is flat</strong> — 0.95 to 1.00 everywhere.</p>
<p>. . .</p>
<p>Young cohorts are homogeneous on identity <strong>specifically</strong>, not in general.</p>
<p>That is the discriminating evidence.</p>
</div></div>
</section></section>
<section>
<section id="the-cohort-we-cannot-predict" class="title-slide slide level1 center">
<h1>The Cohort We Cannot Predict</h1>

</section>
<section id="unpredictable-on-both-outcomes" class="slide level2">
<h2>Unpredictable on Both Outcomes</h2>
<p><strong>Vote choice:</strong> full-model AUC <strong>0.68–0.76</strong> under 40, against <strong>0.90–0.93</strong> over 60.</p>
<p>Two-thirds of that gap survives adding identity, cross-Strait position, and media together.</p>
<div class="fragment">
<p><strong>Turnout:</strong> self-reported, inflated <strong>13–20 points</strong>, compressed against a ceiling.</p>
<p>Heterogeneous effects could not be estimated at all — the latent solution partitioned on turnout, not engagement.</p>
</div>
<div class="fragment">
<p><strong>The cohort that matters most to the argument is the one we predict least well — on both quantities.</strong></p>
</div>
</section>
<section id="why-identity-stops-discriminating" class="slide level2">
<h2>Why: Identity Stops Discriminating</h2>
<div class="columns">
<div class="column" style="width:60%;">
<p><a href="output/figures/figG5_predictability.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img data-src="output/figures/figG5_predictability.png"></a></p>
</div><div class="column" style="width:40%;">
<p>China factor adds <strong>0.154</strong> for the young, <strong>0.251</strong> for the old.</p>
<p>. . .</p>
<p>Media adds ~<strong>0.03</strong> — flat across all cohorts.</p>
<p>. . .</p>
<p>The gap narrows because identity does <strong>less</strong>, not because media does more.</p>
<p>. . .</p>
<p>Nothing we have replaces it.</p>
</div></div>
</section>
<section id="what-the-synthetic-data-is-actually-for" class="slide level2">
<h2>What the Synthetic Data Is Actually For</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Synthetic data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Marginals, joint distributions</td>
<td>reproduced almost exactly (TVD 0.001–0.016)</td>
</tr>
<tr class="even">
<td>Individual prediction (AUC)</td>
<td>no contribution</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Not a tension. <strong>The same finding from two directions.</strong></p>
</div>
<div class="fragment">
<p>A <strong>variance-reduction device for distributional quantities</strong> — not an information-generation device for individual ones.</p>
</div>
<div class="fragment">
<p>Augmentation gains were largest for the <strong>largest</strong> sample. We tested it against the wrong target.</p>
</div>
</section></section>
<section>
<section id="would-better-data-help" class="title-slide slide level1 center">
<h1>Would Better Data Help?</h1>

</section>
<section id="social-media-the-variance-argument-fails" class="slide level2">
<h2>Social Media: The Variance Argument Fails</h2>
<p><strong>Only 2020 has the platform battery.</strong> 2016 has none; 2024 has one generic item.</p>
<div class="fragment">
<p>Media entropy among 20–29 is already <strong>0.96–0.98</strong>. TV exposure is <em>not</em> low-variance for them.</p>
</div>
<div class="fragment">
<p>LINE and YouTube adoption is <strong>near-universal</strong> — a use-indicator would be near-constant in exactly the cohort needing discrimination.</p>
<p>Same failure mode as identity.</p>
</div>
</section>
<section id="scraped-data-is-worse-not-better" class="slide level2">
<h2>Scraped Data Is Worse, Not Better</h2>
<p>PTT posters, YouTube commenters, Facebook sharers are <strong>not samples of users</strong>.</p>
<p>They are the vocal minority — most engaged, most partisan, most willing to broadcast.</p>
<div class="fragment">
<p><strong>A tail-weighted measure for a median-voter prediction problem.</strong></p>
</div>
<div class="fragment">
<p>莊伯仲 warned of exactly this at the TPOC symposium: 同溫層偏誤.</p>
</div>
<div class="fragment">
<p>And no platform carries age. Linkage runs through geography — back to the ecological problem.</p>
</div>
</section>
<section id="aggregate-data-will-not-rescue-turnout" class="slide level2">
<h2>Aggregate Data Will Not Rescue Turnout</h2>
<p>CEC publishes <strong>registered voters</strong> by age. That is the denominator.</p>
<p><strong>Turnout by age</strong>: we could not confirm it is published.</p>
<div class="fragment">
<p>So age-specific turnout is an <em>ecological inference</em> problem, not a retrieval one.</p>
</div>
<div class="fragment">
<p>And EI is badly suited to age here: young-heavy districts <strong>are</strong> Taipei and Hsinchu; old-heavy districts <strong>are</strong> Yunlin and Pingtung.</p>
<p>Age composition is confounded with partisan geography.</p>
</div>
</section>
<section id="where-this-points" class="slide level2">
<h2>Where This Points</h2>
<p>Every difficulty is about recovering <strong>individual-level</strong> information on young voters.</p>
<div class="fragment">
<p>None obstructs <strong>aggregate</strong> estimation — and aggregates are what the synthetic data already reproduces well.</p>
</div>
<div class="fragment">
<p><strong>Change the estimand.</strong> DPP share within an age group, not the vote of a given respondent.</p>
</div>
<div class="fragment">
<p>For forecasting and allocation that is the quantity actually wanted. It does not license claims about individual behaviour.</p>
</div>
</section>
<section id="conclusion" class="slide level2">
<h2>Conclusion</h2>
<p><strong>A closing cleavage does not just become less contested.</strong> It loses its power to discriminate where closure is most complete.</p>
<div class="fragment">
<p>Media effects among the young double: 10.2 → 22.6</p>
<p>Identity effects among the young <strong>more than halve</strong>: 48.7 → 22.3</p>
</div>
<div class="fragment">
<p>Three qualifications: turnout shows no gradient; the mechanism weakens in 2024 (rho 0.6); the predictive payoff is small.</p>
</div>
<div class="fragment">
<p>Three cross-sections give a <strong>snapshot</strong>, not a film. Cohort, period, and life cycle are not separable here.</p>
</div>
</section>
<section id="section-1" class="slide level2 center">
<h2></h2>
<h2>
Thank You
</h2>
<p><br>
</p>
<p><strong>Karl Ho</strong> — karlho@gmail.com</p>
<p><strong>John Marion Glendenning</strong> — John.Glendenning@UTDallas.edu</p>
<p><br>
</p>
<h6>
Data: Taiwan’s Election and Democratization Study, 2016 · 2020 · 2024
</h6>
</section></section>
<section>
<section id="additional-material" class="title-slide slide level1 center">
<h1>Additional Material</h1>
<h4>
Slides below are held for discussion
</h4>
</section>
<section id="silicon-samples-are-already-commercial" class="slide level2">
<h2>Silicon Samples Are Already Commercial</h2>
<p><strong>TPOC 台灣議題研究中心</strong>, August 2026:</p>
<ul>
<li class="fragment">3,000 AI agents, 28 attributes, 26 years of polling data</li>
<li class="fragment">Benchmarked against Meilidao and TVBS phone polls</li>
<li class="fragment"><strong>Average error: 4.56 percentage points</strong></li>
<li class="fragment">Subscription launched September — NT$100 per question</li>
</ul>
</section>
<section id="three-warnings-from-that-room" class="slide level2">
<h2>Three Warnings From That Room</h2>
<p><strong>Variance compression.</strong> NTU’s 馮勃翰: AI answers cluster in middle options. <em>Bisbee, replicated in Taiwan.</em></p>
<div class="fragment">
<p><strong>Echo-chamber bias.</strong> 莊伯仲: feeding agents social media produces 同溫層偏誤.</p>
</div>
<div class="fragment">
<p><strong>Ecological fallacy.</strong> UT Austin’s 林澤民: AI agents are prone to it.</p>
</div>
<div class="fragment">
<p><strong>Bayesian calibration.</strong> 謝邦昌: hybrid human-agent designs will require it.</p>
</div>
</section>
<section id="turnout-is-not-vote-choice" class="slide level2">
<h2>Turnout Is Not Vote Choice</h2>
<p>Rank correlation of media effect with age:</p>
<p><strong>Vote choice:</strong> −0.9, −0.8, −0.9</p>
<p><strong>Turnout:</strong> +0.2, +0.4, +0.1</p>
<div class="fragment">
<p>Turnout effects are small — 1.5 to 6.0 points against 3.0 to 22.6.</p>
</div>
<div class="fragment">
<p>Self-reported turnout runs far above official. We read this as <strong>uninformative</strong>, not null.</p>
</div>
</section>
<section id="does-synthetic-augmentation-help" class="slide level2">
<h2>Does Synthetic Augmentation Help?</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p><a href="output/figures/figG6_augmentation.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img data-src="output/figures/figG6_augmentation.png"></a></p>
</div><div class="column" style="width:42%;">
<p><strong>It does not.</strong></p>
<p>Mean gain: 40–59 = <strong>+0.026</strong>, under 40 = <strong>+0.011</strong>, 60+ = <strong>+0.006</strong>.</p>
<p>. . .</p>
<p>The largest gain goes to the <strong>largest</strong> sample — backwards from the sparsity story.</p>
<p>. . .</p>
<p>Two of three under-40 gains are ≈ 0.</p>
</div></div>
</section>
<section id="the-methodological-point" class="slide level2">
<h2>The Methodological Point</h2>
<p>Zaller predicts heterogeneity in media effects by <strong>political awareness</strong>.</p>
<div class="fragment">
<p>This suggests a complementary axis: heterogeneity by <strong>how much room the organizing variable has left to move</strong> within a subgroup.</p>
</div>
<div class="fragment">
<p>Effect heterogeneity should be estimated with respect to the distribution of the dominant cleavage — not assumed uniform.</p>
</div>
</section>
<section id="the-measurement-caveat" class="slide level2">
<h2>The Measurement Caveat</h2>
<p>Our media variable is <strong>television-only</strong> — what TEDS supports consistently across all three waves.</p>
<div class="fragment">
<p>This understates young-voter exposure specifically. LINE, PTT, and Dcard carry political content the instrument does not capture.</p>
</div>
<div class="fragment">
<p>The rising “None” category among the young means <strong>absence of television news</strong>, not absence of political information.</p>
</div>
<div class="fragment">
<p><strong>This works against the hypothesis.</strong> If young voters get partisan content through unobserved channels and we still recover larger television effects, the true asymmetry is larger.</p>
</div>
</section>
<section id="media-diet-by-cohort" class="slide level2">
<h2>Media Diet by Cohort</h2>
<p><a href="output/figures/figG4_media_diet_by_cohort.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img data-src="output/figures/figG4_media_diet_by_cohort.png" style="width:76.0%"></a></p>
</section>
<section id="why-bayesian-networks-not-silicon-samples" class="slide level2">
<h2>Why Bayesian Networks, Not Silicon Samples</h2>
<p><strong>Argyle et al.&nbsp;(2023):</strong> condition an LLM on a demographic backstory. Tetrachoric correlations above 0.9.</p>
<div class="fragment">
<p><strong>Bisbee et al.&nbsp;(2024):</strong> compressed variance, 48% of coefficients differ significantly, prompt sensitivity, temporal instability, demand effects.</p>
</div>
<div class="fragment">
<p><strong>Santurkar et al.&nbsp;(2023):</strong> LLMs reflect liberal, educated, Western opinion.</p>
</div>
<div class="fragment">
<p>The deeper problem: none of those failures is <strong>diagnosable from inside the method</strong>.</p>
</div>
</section>
<section id="one-quantity-two-approaches" class="slide level2">
<h2>One Quantity, Two Approaches</h2>
<p><span class="math display">\[P(\text{DPP vote} \mid \text{Age} = 20\text{–}29, \text{Media} = \text{Green})\]</span></p>
<div class="fragment">
<p><strong>Silicon sample:</strong> write a prompt, sample, tabulate. Traceable to nothing.</p>
</div>
<div class="fragment">
<p><strong>Bayesian network:</strong> read from a conditional probability table fitted to TEDS respondents in that cell.</p>
<p>Inspectable. Cell count checkable. Provenance stateable.</p>
</div>
</section>
<section id="why-latent-class-analysis-first" class="slide level2">
<h2>Why Latent Class Analysis First</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Specification</th>
<th style="text-align: right;">Configurations</th>
<th style="text-align: right;">Free parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No latent segment</td>
<td style="text-align: right;">6,480</td>
<td style="text-align: right;">19,440</td>
</tr>
<tr class="even">
<td>Latent segment, k = 6</td>
<td style="text-align: right;">324</td>
<td style="text-align: right;">972</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Wave n is in the low thousands. <strong>Twenty-fold reduction.</strong></p>
</div>
<div class="fragment">
<p>It does not create information. It imposes a constraint — all demographic variation acts on vote choice <em>through</em> the segment.</p>
</div>
</section>
<section id="media-coding-alignment-moves" class="slide level2">
<h2>Media Coding: Alignment Moves</h2>
<p><strong>Huang (2009)</strong> codes Eastern Television and Era as <strong>pan-Blue</strong> for 2008.</p>
<p><strong>2020 audience rankings</strong> place both on the <strong>pan-Green</strong> side.</p>
<div class="fragment">
<p>No single time-invariant coding is right for all three waves.</p>
</div>
<div class="fragment">
<p>We withhold partisan classification from every contested outlet — which <strong>attenuates</strong> the estimated effect toward zero.</p>
<p>The error runs against our own conclusion.</p>
</div>
</section>
<section id="cohort-versus-period" class="slide level2">
<h2>Cohort Versus Period</h2>
<p>Three cross-sections cannot separate the two.</p>
<div class="fragment">
<p>Is the pattern fixed at socialization, or do individuals become less media-responsive as they age?</p>
</div>
<div class="fragment">
<p>TEDS panel components would support a dynamic specification. This is the first item in future research.</p>
</div>
</section>
<section id="future-research" class="slide level2">
<h2>Future Research</h2>
<ul>
<li class="fragment"><strong>Platform-specific measurement</strong> — LINE, PTT, Dcard for the waves where available</li>
<li class="fragment"><strong>Cohort versus period</strong> — dynamic Bayesian networks on the panel component</li>
<li class="fragment"><strong>The third-force channel</strong> — model “Other” as substantive, not residual</li>
<li class="fragment"><strong>Extend backward</strong> — 2008 and 2012 waves to test whether the pattern tracks the progressive closure of the cleavage</li>
</ul>
</section>
<section id="references" class="slide level2 smaller">
<h2>References</h2>
<ul>
<li>Achen, C.H. and T.Y. Wang, eds.&nbsp;2017. <em>The Taiwan Voter</em>. University of Michigan Press.</li>
<li>Argyle, L.P. et al.&nbsp;2023. Out of one, many. <em>Political Analysis</em> 31: 337–351.</li>
<li>Bisbee, J. et al.&nbsp;2024. Synthetic replacements for human survey data? <em>Political Analysis</em> 32: 401–416.</li>
<li>Ho, K. and J.M. Glendenning. 2026. Media Effects and Party Support Volatility in US. SPSA.</li>
<li>Huang, C.-L. 2009. The Changing Roles of the Media in Taiwan’s Democratization Process. Brookings.</li>
<li>Linzer, D.A. and J.B. Lewis. 2011. poLCA. <em>Journal of Statistical Software</em> 42.</li>
<li>Pearl, J. 2009. <em>Causality</em>, 2nd ed.&nbsp;Cambridge University Press.</li>
<li>Santurkar, S. et al.&nbsp;2023. Whose opinions do language models reflect? <em>ICML</em>.</li>
<li>Scutari, M. 2010. Learning Bayesian networks with bnlearn. <em>JSS</em> 35.</li>
<li>Zaller, J.R. 1992. <em>The Nature and Origins of Mass Opinion</em>. Cambridge University Press.</li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="eppslogo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>Generational Cleavages in Media Effects: Evidence from Taiwan</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="cgots2026_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="cgots2026_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="cgots2026_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="cgots2026_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="cgots2026_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="cgots2026_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="cgots2026_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="cgots2026_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="cgots2026_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="cgots2026_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    <script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
    (function() {
      let previousOnload = window.onload;
      window.onload = () => {
        if (previousOnload) {
          previousOnload();
        }
        lightboxQuarto.on('slide_before_load', (data) => {
          const { slideIndex, slideNode, slideConfig, player, trigger } = data;
          const href = trigger.getAttribute('href');
          if (href !== null) {
            const imgEl = window.document.querySelector(`a[href="${href}"] img`);
            if (imgEl !== null) {
              const srcAttr = imgEl.getAttribute("src");
              if (srcAttr && srcAttr.startsWith("data:")) {
                slideConfig.href = srcAttr;
              }
            }
          } 
        });
      
        lightboxQuarto.on('slide_after_load', (data) => {
          const { slideIndex, slideNode, slideConfig, player, trigger } = data;
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(slideNode);
          }
        });
      
      };
      
    })();
              </script>
    

</body></html>